### Today we are going to perform the simple classification of the amazon reviews' sentiment.

### Please, download the dataset amazon_baby.csv.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.linear_model import LogisticRegression

def remove_punctuation(text):
    import string
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

import io
from google.colab import files
import csv

#uploaded = files.upload()
#baby_df = pd.read_csv(io.StringIO(uploaded['amazon_baby.csv'].decode('utf-8')))

baby_df = pd.read_csv('amazon_baby.csv')
baby_df.head()

name  \
0                           Planetwise Flannel Wipes   
1                              Planetwise Wipe Pouch   
2                Annas Dream Full Quilt with 2 Shams   
3  Stop Pacifier Sucking without tears with Thumb...   
4  Stop Pacifier Sucking without tears with Thumb...   

                                              review  rating  
0  These flannel wipes are OK, but in my opinion ...       3  
1  it came early and was not disappointed. i love...       5  
2  Very soft and comfortable and warmer than it l...       5  
3  This is a product well worth the purchase.  I ...       5  
4  All of my kids have cried non-stop when I trie...       5

## Exercise 1 (data preparation)
a) Remove punctuation from reviews using the given function.   
b) Replace all missing (nan) revies with empty "" string.  
c) Drop all the entries with rating = 3, as they have neutral sentiment.   
d) Set all positive ($\geq$4) ratings to 1 and negative($\leq$2) to -1.

In [3]:
#b)

baby_df.review = baby_df.review.fillna('')
#short test:
baby_df["review"][38] == baby_df["review"][38]
baby_df["review"][38]

''

Conclusion: Firstly we must replace all missing (nan) reviews with empty string, because we can't remove punctuation from reviews if we don't do this.

In [4]:
#a)
def remove_punctuation(text):
    import string
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

#short test: 
baby_df["review"][4] == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'
remove_punctuation(baby_df["review"][4]) == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'
baby_df['review'] = baby_df['review'].apply(lambda x: remove_punctuation(x))
baby_df["review"]

0         These flannel wipes are OK but in my opinion n...
1         it came early and was not disappointed i love ...
2         Very soft and comfortable and warmer than it l...
3         This is a product well worth the purchase  I h...
4         All of my kids have cried nonstop when I tried...
                                ...                        
183526    Such a great idea very handy to have and look ...
183527    This product rocks  It is a great blend of fun...
183528    This item looks great and cool for my kidsI kn...
183529    I am extremely happy with this product I have ...
183530    I love this product very mush  I have bought m...
Name: review, Length: 183531, dtype: object

Conclusions: As we can see, the puntuations were removed.

In [5]:
baby_df['rating'].size

183531

In [6]:
#c)
baby_df = baby_df[baby_df.rating != 3]
#short test:
sum(baby_df["rating"] == 3)

0

In [7]:
baby_df['rating'].size

166752

In [8]:
#d) 
baby_df['rating'].loc[baby_df['rating'] <= 2, ] = -1
baby_df['rating'].loc[baby_df['rating'] >= 4] = 1
#short test:


/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [9]:
sum(baby_df["rating"]**2 != 1)

0

In [10]:
baby_df.head(20)

name  \
1                               Planetwise Wipe Pouch   
2                 Annas Dream Full Quilt with 2 Shams   
3   Stop Pacifier Sucking without tears with Thumb...   
4   Stop Pacifier Sucking without tears with Thumb...   
5   Stop Pacifier Sucking without tears with Thumb...   
6             A Tale of Baby's Days with Peter Rabbit   
7   Baby Tracker&reg; - Daily Childcare Journal, S...   
8   Baby Tracker&reg; - Daily Childcare Journal, S...   
9   Baby Tracker&reg; - Daily Childcare Journal, S...   
10  Baby Tracker&reg; - Daily Childcare Journal, S...   
11  Baby Tracker&reg; - Daily Childcare Journal, S...   
12  Baby Tracker&reg; - Daily Childcare Journal, S...   
14     Nature's Lullabies First Year Sticker Calendar   
15     Nature's Lullabies First Year Sticker Calendar   
16     Nature's Lullabies First Year Sticker Calendar   
17    Nature's Lullabies Second Year Sticker Calendar   
18    Nature's Lullabies Second Year Sticker Calendar   
19    Nature's Lullabies Second Year Sticker Calendar   
20    Nature's Lullabies Second Year Sticker Calendar   
21    Nature's Lullabies Second Year Sticker Calendar   

                                               review  rating  
1   it came early and was not disappointed i love ...       1  
2   Very soft and comfortable and warmer than it l...       1  
3   This is a product well worth the purchase  I h...       1  
4   All of my kids have cried nonstop when I tried...       1  
5   When the Binky Fairy came to our house we didn...       1  
6   Lovely book its bound tightly so you may not b...       1  
7   Perfect for new parents We were able to keep t...       1  
8   A friend of mine pinned this product on Pinter...       1  
9   This has been an easy way for my nanny to reco...       1  
10  I love this journal and our nanny uses it ever...       1  
11  This book is perfect  Im a first time new mom ...       1  
12  I originally just gave the nanny a pad of pape...       1  
14  Space for monthly photos info and a lot of use...       1  
15  I bought this calender for myself for my secon...       1  
16  I love this little calender you can keep track...       1  
17  This was the only calender I could find for th...       1  
18  I completed a calendar for my sons first year ...       1  
19  We wanted to get something to keep track of ou...       1  
20  I had a hard time finding a second year calend...       1  
21  I only purchased a secondyear calendar for my ...      -1

Conclusions: As we can see, all elements with rating >= 4 were replaced with value 1 and with rating <= 2 by value -1 and there is no ratings with value of 3.

## CountVectorizer
In order to analyze strings, we need to assign them numerical values. We will use one of the simplest string representation, which transforms strings into the $n$ dimensional vectors. The number of dimensions will be the size of our dictionary, and then the values of the vector will represent the number of appereances of the given word in the sentence.

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
reviews_train_example = ["We like apples",
                   "We hate oranges",
                   "I adore bananas",
                   "We like like apples and oranges",
                   "They dislike bananas"]

X_train_example = vectorizer.fit_transform(reviews_train_example)

print(vectorizer.get_feature_names())
print(X_train_example.todense())



['adore', 'and', 'apples', 'bananas', 'dislike', 'hate', 'like', 'oranges', 'they', 'we']
[[0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 2 1 0 1]
 [0 0 0 1 1 0 0 0 1 0]]


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [12]:
reviews_test_example = ["They like bananas",
                   "We hate oranges bananas and apples",
                   "We love bananas"] #New word!

X_test_example = vectorizer.transform(reviews_test_example)

print(X_test_example.todense())

[[0 0 0 1 0 0 1 0 1 0]
 [0 1 1 1 0 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 1]]


We should acknowledge few facts. Firstly, CountVectorizer does not take order into account. Secondly, it ignores one-letter words (this can be changed during initialization). Finally, for test values, CountVectorizer ignores words which are not in it's dictionary.

## Exercise 2 
a) Split dataset into training and test sets.     
b) Transform reviews into vectors using CountVectorizer. 

In [34]:
#a)

vectorizer = CountVectorizer()

from sklearn.model_selection import train_test_split
train, test = train_test_split(baby_df, test_size=0.3)

In [35]:
#b)
X_train_baby = vectorizer.fit_transform(train['review'])

X_test_baby = vectorizer.transform(test['review'])


## Exercise 3 
a) Train LogisticRegression model on training data (reviews processed with CountVectorizer, ratings as they were).   
b) Print 10 most positive and 10 most negative words.

In [37]:
#a)
model = LogisticRegression()
model.fit(X_train_baby, train['rating'])

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [38]:
#b)

coef = np.argsort(model.coef_[0])
names = vectorizer.get_feature_names()

print("Top 10 negative words: ")
for i in range(10):
  print(names[coef[i]])
print()

print("Top 10 positive words: ")
for i in range(1, 11, 1):
  print(names[coef[-i]])

#hint: model.coef_, vectorizer.get_feature_names()

Top 10 negative words: 
worst
poorly
disappointing
worthless
disappointment
concept
horrible
disappointed
overpriced
theory

Top 10 positive words: 
satisfied
awesome
excellent
worry
perfect
amazing
skeptical
lifesaver
complaint
loves


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


## Exercise 4 
a) Predict the sentiment of test data reviews.   
b) Predict the sentiment of test data reviews in terms of probability.   
c) Find five most positive and most negative reviews.   
d) Calculate the accuracy of predictions.

In [39]:
#a)
model.predict(X_test_baby)

array([-1,  1,  1, ..., -1,  1,  1])

In [40]:
#b)
prob_results = model.predict_proba(X_test_baby)
prob_results
#hint: model.predict_proba()

array([[0.87587515, 0.12412485],
       [0.12255121, 0.87744879],
       [0.01378696, 0.98621304],
       ...,
       [0.88118316, 0.11881684],
       [0.00307872, 0.99692128],
       [0.14172315, 0.85827685]])

In [42]:
#c) 
positive = np.argsort(prob_results[:, 0])
negative = np.argsort(prob_results[:, 1])

print("Positive reviews: ")
print(test['review'].iloc[positive[0]])
print(test['review'].iloc[positive[1]])
print(test['review'].iloc[positive[2]])
print(test['review'].iloc[positive[3]])
print(test['review'].iloc[positive[4]])

print()

print("Negative reviews: ")
print(test['review'].iloc[negative[0]])
print(test['review'].iloc[negative[1]])
print(test['review'].iloc[negative[2]])
print(test['review'].iloc[negative[3]])
print(test['review'].iloc[negative[4]])

#hint: use the results of b)

Positive reviews: 
I purchased this car seat online through BRUS about a month ago and have the Gemni purple color It was all that was available and even though I have a boy its a very deep purple and not girlieI have very similar sentiments as the first reviewer Prior to buying this one I bought and tested the Radian Diono SafetyFirst Air 65 Britax Pavilion and Recaro ProRide This car seat was my absolute favorite The Recaro ProRide was up there except its latch anchor belt is surprisinglyridiculously too short and I could not install it into my 2008 Hyundai Tuscan a compact SUV I had no problem installing any of the other car seats with the latch anchor system so the Recaro was completely out of the running which was a bummer because it did seem very nice Right now we are using it rearfacing for my 9month old who recently grew out of his Chicco Keyfit He is approximately 28 inches tall and 19 lbs his head in the infant seat while sitting was more than an inch from the edge We have su

In [43]:
#d) 

model.score(X_test_baby, test['rating'])

0.931675528725063

## Exercise 5
In this exercise we will limit the dictionary of CountVectorizer to the set of significant words, defined below.


a) Redo exercises 2-5 using limited dictionary.   
b) Check the impact of all the words from the dictionary.   
c) Compare accuracy of predictions and the time of evaluation.

In [44]:
significant_words = ['love','great','easy','old','little','perfect','loves','well','able','car','broke','less','even','waste','disappointed','work','product','money','would','return']

In [45]:
#a)
vectorizer_significant_words = CountVectorizer(vocabulary=significant_words)

X_train_words = vectorizer_significant_words.fit_transform(train['review'])
X_test_words = vectorizer_significant_words.transform(test['review'])

model_significant_words = LogisticRegression()

model_significant_words.fit(X_train_words, train['rating'])

LogisticRegression()

In [46]:
coef = np.argsort(model_significant_words.coef_[0])
names = vectorizer_significant_words.get_feature_names()

print("Top 10 negative words: ")
for i in range(10):
  print(names[coef[i]])
print()

print("Top 10 positive words: ")
for i in range(1, 11, 1):
  print(names[coef[-i]])

Top 10 negative words: 
disappointed
return
waste
broke
money
work
even
would
product
less

Top 10 positive words: 
loves
perfect
love
easy
great
little
well
able
old
car


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [47]:
model_significant_words.predict(X_test_words)

array([1, 1, 1, ..., 1, 1, 1])

In [48]:
prob_results_words = model_significant_words.predict_proba(X_test_words)
prob_results_words

array([[0.21671122, 0.78328878],
       [0.21671122, 0.78328878],
       [0.21671122, 0.78328878],
       ...,
       [0.273957  , 0.726043  ],
       [0.03693419, 0.96306581],
       [0.16221522, 0.83778478]])

In [54]:
positive_words = np.argsort(prob_results_words[:, 0])
negative_words = np.argsort(prob_results_words[:, 1])
print("Positive reviews: ")
print(test['review'].iloc[positive_words[0]])
print(test['review'].iloc[positive_words[1]])
print(test['review'].iloc[positive_words[2]])
print(test['review'].iloc[positive_words[3]])
print(test['review'].iloc[positive_words[4]])

print()

print("Negative reviews: ")
print(test['review'].iloc[negative_words[0]])
print(test['review'].iloc[negative_words[1]])
print(test['review'].iloc[negative_words[2]])
print(test['review'].iloc[negative_words[3]])
print(test['review'].iloc[negative_words[4]])

Positive reviews: 
Ive posted an UPDATE at the endFirst let me state that I have been buying products from Amazon for the past 12 years  I love Amazon  I love the reviews because they have always played a part sometimes more sometimes less in the products I decide to purchase  For some reason I have never left a review I know  Until now  I feel such an urge to express how much my husband and I love this strollerMy first son will turn 7 next month  We purchased an Evenflo strollercar seat travel system for him in 2005  We hated it  We used the car seat but never EVER used the stroller  It was big bulky heavy and a pain in the rear  I think my husband hated it even more than I did  I wore my first son everywhere instead of putting him in a stroller  Fast forward to 6 years later and we have our second son in September of 2011  I researched for months  I wanted to find a stroller that had several qualities  Looks  As shallow as it may seem I wanted a stroller that wasnt ugly  I wasnt inte

In [50]:
model_significant_words.score(X_test_words, test['rating'])

0.8695678247311398

In [51]:
#b)

coef_list = model_significant_words.coef_[0]
names_list = vectorizer_significant_words.get_feature_names()

for i in range(len(names)):
  print('name: ' + str(names_list[i]) + ' -->  coef: ' + str(coef_list[i]))


name: love -->  coef: 1.3628888506244097
name: great -->  coef: 0.9542428980397074
name: easy -->  coef: 1.2238972673406527
name: old -->  coef: 0.08394902685079346
name: little -->  coef: 0.5109027089779152
name: perfect -->  coef: 1.4385680797211253
name: loves -->  coef: 1.7295365079090033
name: well -->  coef: 0.4972550960055549
name: able -->  coef: 0.2178320952936153
name: car -->  coef: 0.06627052597219642
name: broke -->  coef: -1.6842523140873447
name: less -->  coef: -0.14035359430782704
name: even -->  coef: -0.5116834145822656
name: waste -->  coef: -1.976825848814431
name: disappointed -->  coef: -2.328115510397404
name: work -->  coef: -0.6222560379923029
name: product -->  coef: -0.3102976768537777
name: money -->  coef: -0.8936581775660614
name: would -->  coef: -0.35442577249322904
name: return -->  coef: -2.099789153855098


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [53]:
#c)
print(model.score(X_test_baby, test['rating']))
print(model_significant_words.score(X_test_words, test['rating']))

print()


import time

start = time.time()
model_significant_words.fit(X_test_words, test['rating'])
end = time.time()
print("Time significant: " + str(end - start))

start = time.time()
model.fit(X_test_baby, test['rating'])
end = time.time()
print("Time ordinary: " + str(end - start))


#hint: %time, %timeit

0.967476912005757
0.8423819613800824

Time significant: 0.20718979835510254
Time ordinary: 9.134341716766357


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


As we can see accuracy of predictions is worse for significant words list, but time of evaluation is much smaller.